language: go
go: 1.3
install:
    - go get github.com/mitchellh/gox
    - gvm use 1.3
    - gox -build-toolchain -osarch=windows/386
script: make
deploy:
  provider: releases
  api_key:
    secure: cL0ByoBtiYrBKa9vkka5+PLJpnq3yfTPLLIlwbm25zInSwCgtlqIyUwYflyUCZOSVnM3vcReiegPaPMy0j88HIxIULt5dECDwuS0/WDGNZ008Tf8Uc6aYZai8DSaOSdlj1QB/DANJQ2xM2vXFp85hq9FMXH5VJUwuLSNWBwkBK0=
  file: localserver-win32.zip
  skip_cleanup: true
  on:
    tags: true
    repo: methane/localserver
